### ISSUE TITLE
Function to convert names

### ISSUE THREAD

**Issue by youraccount** [fadb/go-fadb#4]
`Some Name` -> `SomeName`
`some-name` -> `someName`
`some_name` -> `someName`
`some name (1)` -> `somename1`

*  all but (a-zA-Z0-9_-) removed
* spaces removed
* dashes removed with next capitalized
* underscores remoted with next capitalized

**Comment by robmuh** [comment]
Completed in [go-safenames](http://github.com/fadb/go-safenames). Closing #4
