### ISSUE TITLE
Pointer to Path converter 

### ISSUE THREAD

**Issue by youraccount** [fadb/go-fadb#9]
Simple version finds the file that realizes the object:

`summer.pro.students.betropper` -> `summer/pro/students/betropper/_.toml`

But also has to see:

`summer.pro.students.betropper` -> `summer/pro/students/betropper.toml`

But also has to see parent files. sp of `students` is a table in `pro`:

`summer.pro.students.betropper` -> `summer/pro.toml`

**Comment by robmuh** [comment]
Implemented in `pointer.go` and `pointer_test.go`. Closing #9
